// Synthetic tests of the existing draft transport only. No live Google/Microsoft calls.
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {makeHandler} from '../api/crm-session.js';
import {nativeCall,resolveBrowserSession,withBrowserSession,MAX_MS} from '../server/crm-session/core.js';
import {harness,response,ORIGIN,SESSION_COOKIE} from './session-support.mjs';
const knownErrors=['This record changed on another device. Refresh before saving.','Record no longer exists. Refresh and retry.','Name is required','Name is too long','Invalid date','Invalid amount','Invalid email','Linked record not found','A company with that exact name already exists'];
for(const error of knownErrors)test('captured safe native business rejection remains distinguishable: '+error,async()=>{
 await assert.rejects(nativeCall('saveRecord',['synthetic','Tasks',{}],{fetcher:async()=>({ok:true,json:async()=>({ok:false,error})})}),e=>e.message===error);
});
for(const fn of ['getState','googleSignIn'])test('business error mapping does not broaden unrelated method contracts: '+fn,async()=>{
 await assert.rejects(nativeCall(fn,[],{fetcher:async()=>({ok:true,json:async()=>({ok:false,error:'Name is required'})})}),new RegExp(fn==='googleSignIn'?'SIGNIN_REJECTED':'CRM_CONNECTION_UNCERTAIN'));
});
test('unreviewed native error stays sanitized and is not retried',async()=>{let calls=0;await assert.rejects(nativeCall('saveRecord',[],{fetcher:async()=>{calls++;return {ok:true,json:async()=>({ok:false,error:'private synthetic token data'})};}}),/CRM_CONNECTION_UNCERTAIN/);assert.equal(calls,1);});
function request(h,m,body){return {method:'POST',headers:{origin:ORIGIN,host:'api.thesmartysolution.com','content-type':'application/json','x-tss-crm-request':'1','x-tss-crm-csrf':m.csrf,cookie:SESSION_COOKIE+'='+h.jar[SESSION_COOKIE]},body};}
async function expiredDuringCheck(op){const h=harness(),m=(await h.login()).value.result;for(const s of h.store.values())s.expiresAt+=MAX_MS;h.behavior.check={expiresAt:h.clock()+MAX_MS*2};h.advance(MAX_MS-1);const call=async(fn,args)=>{const v=await h.call(fn,args);if(fn==='checkSession')h.advance(2);return v;};const r=response();await makeHandler({env:h.env,clock:h.clock,call})(request(h,m,{op,marker:m.marker,fn:'saveRecord',args:['Tasks',{name:'Synthetic'}]}),r);return {h,r};}
for(const op of ['resume','rpc'])test('cookie deadline is rechecked after delayed native validation: '+op,async()=>{const {h,r}=await expiredDuringCheck(op);assert.equal(r.value.error,'AUTH_REQUIRED');assert.equal(h.calls.filter(x=>x.fn==='saveRecord').length,0);});
test('adapter validates the native result against the post-await clock',async()=>{const h=harness(),m=(await h.login()).value.result;h.behavior.check={expiresAt:h.clock()+1};const now=h.clock(),call=async(fn,args)=>{const v=await h.call(fn,args);h.advance(2);return v;};await assert.rejects(resolveBrowserSession(request(h,m,{}),m.marker,{env:h.env,now,clock:h.clock,call}),/AUTH_REQUIRED/);});
test('RPC carries narrowed expiry and preserves expiry-only checkSession response',async()=>{const h=harness(),m=(await h.login()).value.result,expiresAt=h.clock()+500;h.behavior.check={expiresAt};const r=await h.invoke({op:'rpc',marker:m.marker,fn:'checkSession',args:[]},{headers:{'x-tss-crm-csrf':m.csrf}});assert.equal(r.value.ok,true);assert.deepEqual(r.value.result,{expiresAt});assert.equal(r.value.sessionExpiresAt,expiresAt);});
test('protected adapters propagate narrowed expiry without changing business payload or cookie headers',async()=>{const h=harness(),m=(await h.login()).value.result,expiresAt=h.clock()+500;h.behavior.check={expiresAt};let calls=0;const handler=withBrowserSession((req,res)=>{calls++;res.setHeader('Set-Cookie','existing-synthetic-cookie');return res.status(200).json({ok:true,result:{saved:true}});},'session',{env:h.env,clock:h.clock,call:h.call});const r=response();await handler(request(h,m,{session:m.marker}),r);assert.equal(calls,1);assert.deepEqual(r.value.result,{saved:true});assert.equal(r.value.sessionExpiresAt,expiresAt);assert.equal(r.headers['set-cookie'],'existing-synthetic-cookie');});
test('known stale-record error is a conflict, not a retryable network outage',async()=>{const h=harness(),m=(await h.login()).value.result;const call=async(fn,args)=>fn==='saveRecord'?nativeCall(fn,args,{fetcher:async()=>({ok:true,json:async()=>({ok:false,error:knownErrors[0]})})}):h.call(fn,args);const r=response();await makeHandler({env:h.env,clock:h.clock,call})(request(h,m,{op:'rpc',marker:m.marker,fn:'saveRecord',args:['Tasks',{}]}),r);assert.equal(r.statusCode,409);assert.equal(r.value.error,knownErrors[0]);});
test('login cannot issue a cookie after the returned native login expiry has elapsed',async()=>{const h=harness(),b=await h.invoke({op:'begin'});h.behavior.ttl=1;h.behavior.check={expiresAt:h.clock()+MAX_MS};const call=async(fn,args)=>{const v=await h.call(fn,args);if(fn==='checkSession')h.advance(2);return v;};const r=response(),m={csrf:b.value.result.csrf};const req=request(h,m,{op:'login',credential:h.credential(b.value.result.nonce),trusted:false});req.headers.cookie=Object.entries(h.jar).map(([k,v])=>k+'='+v).join('; ');await makeHandler({env:h.env,clock:h.clock,call})(req,r);assert.equal(r.value.ok,false);assert.equal(r.headers['set-cookie'],undefined);});
function clientFixture(){let now=1791118800000,replyExpiry,delay=0;const calls=[],observed=[],meta={marker:'tss-cookie-v1:'+'a'.repeat(32),csrf:'b'.repeat(64),expiresAt:now+1000,trusted:false};const c={AbortController,Error,TypeError,setTimeout,clearTimeout,Date,localStorage:{getItem(){return null},setItem(){throw Error('No storage write expected')},removeItem(){}},fetch:async(url,options)=>{const body=options.body?JSON.parse(options.body):{};calls.push(body);if(options.method==='GET')return {ok:true,json:async()=>({ok:true,enabled:true})};if(body.op==='resume')return {ok:true,json:async()=>({ok:true,result:{...meta}})};now+=delay;return {ok:true,json:async()=>({ok:true,result:{saved:true},...(replyExpiry===undefined?{}:{sessionExpiresAt:replyExpiry})})};}};vm.createContext(c);vm.runInContext(fs.readFileSync(new URL('../crm/session-continuity.js',import.meta.url),'utf8'),c);const api=c.TSSBrowserSession.create({clock:()=>now,expiryChanged:e=>observed.push(e)});return {api,calls,meta,observed,advance:x=>now+=x,reply:x=>replyExpiry=x,delay:x=>delay=x,clock:()=>now};}
async function initialized(){const f=clientFixture();await f.api.initialize();await f.api.resume();return f;}
test('client propagates earlier expiry without re-running readiness or storing a secret',async()=>{const f=await initialized(),end=f.clock()+100;f.reply(end);await f.api.rpc('getState',[f.meta.marker]);assert.deepEqual(f.observed,[end]);f.advance(101);const n=f.calls.length;await assert.rejects(f.api.rpc('getState',[f.meta.marker]),/AUTH_REQUIRED/);assert.equal(f.calls.length,n);});
test('a later response never lengthens a previously shortened client deadline',async()=>{const f=await initialized(),end=f.clock()+100;f.reply(end);await f.api.rpc('getState',[f.meta.marker]);f.reply(f.clock()+50000);await f.api.rpc('getState',[f.meta.marker]);f.advance(101);await assert.rejects(f.api.rpc('getState',[f.meta.marker]),/AUTH_REQUIRED/);});
test('service calls check the local deadline before dispatch',async()=>{const f=await initialized();f.advance(1001);const n=f.calls.length;await assert.rejects(f.api.service('/api/outlook/status',{session:f.meta.marker}),/AUTH_REQUIRED/);assert.equal(f.calls.length,n);});
test('known successful write acknowledgement survives expiry during the operation, without retry',async()=>{const f=await initialized();f.reply(f.meta.expiresAt);f.delay(1100);assert.deepEqual(JSON.parse(JSON.stringify(await f.api.rpc('saveRecord',[f.meta.marker,'Tasks',{}]))),{saved:true});assert.equal(f.calls.filter(c=>c.fn==='saveRecord').length,1);await assert.rejects(f.api.rpc('getState',[f.meta.marker]),/AUTH_REQUIRED/);});
for(const v of ['1791118800001',NaN,-1,1.5])test('malformed narrowed expiry fails closed: '+String(v),async()=>{const f=await initialized();f.reply(v);await assert.rejects(f.api.rpc('getState',[f.meta.marker]),/NATIVE_CONTRACT_UNVERIFIED/);});

for(const delay of [54000,56000])test('check and operation share the existing transport budget: '+delay,async()=>{const h=harness(),m=(await h.login()).value.result,budgets=[];const call=async(fn,args,options)=>{budgets.push({fn,ms:options.timeoutMs});const v=await h.call(fn,args);if(fn==='checkSession')h.advance(delay);return v;};const r=response();await makeHandler({env:h.env,clock:h.clock,call})(request(h,m,{op:'rpc',marker:m.marker,fn:'saveRecord',args:['Tasks',{name:'Synthetic'}]}),r);assert.equal(budgets[0].ms,55000);if(delay===54000){assert.equal(budgets[1].ms,1000);assert.equal(r.value.ok,true);}else{assert.equal(budgets.length,1);assert.equal(r.value.error,'CRM_CONNECTION_UNCERTAIN');}});
