import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import {createHash,randomUUID} from 'node:crypto';
const source=readFileSync('command-center/apps-script/CommandCenter.gs','utf8');
function runtime(existing){
 const rows=existing||[];const sheet={getLastRow:()=>rows.length,setFrozenRows(){},getRange(r,c,n=1,w=1){return {getDisplayValues:()=>Array.from({length:n},(_,i)=>Array.from({length:w},(_,j)=>String(rows[r+i-1]?.[c+j-1]??''))),setValues(v){v.forEach((x,i)=>{rows[r+i-1]=x;});return this;},setBackground(){return this;},setFontColor(){return this;}};},appendRow(r){rows.push(r);}};
 const ss={getSheetByName:()=>rows.length?sheet:null,insertSheet:()=>sheet};let saves=0;let current={id:'T1',version:'v1',name:'Keep',custom:0};
 const ctx=vm.createContext({console,Date,SCHEMA:{Tasks:['id','version','name','status','notes','createdAt','updatedAt']},OWNER:'internal@example.test',authHash_:s=>createHash('sha256').update(s).digest('hex'),Utilities:{getUuid:randomUUID},SpreadsheetApp:{flush(){}},LockService:{getScriptLock:()=>({waitLock(){},releaseLock(){}})},requireSession_:t=>{if(t!=='valid')throw Error('AUTH_REQUIRED');},db_:()=>ss,rows_:()=>[current],saveRecordLocked_:(e,x)=>{saves++;current={...current,...x,id:x.id||'T2',updatedAt:'2026-09-22'};return current;},PropertiesService:{getScriptProperties:()=>({getProperty:()=>null})}});
 vm.runInContext(source,ctx);ctx.ccLedger_(ss,true);
 const input={requestId:'request-1234',entity:'Tasks',operation:'update',recordId:'T1',expectedVersion:'v1',fields:{notes:'Prepared'},expectedOutcome:'Update notes'};
 return {ctx,ss,rows,input,propose:()=>ctx.ccPropose('valid',input),saves:()=>saves,change:()=>current.version='v2'};
}
test('AS-01 native gateway rejects unauthenticated requests before data access',()=>{const r=runtime();assert.throws(()=>r.ctx.ccPropose('bad',r.input),/AUTH_REQUIRED/);assert.equal(r.rows.length,1);});
test('AS-02 exact approval required; successful replay cannot dispatch twice',()=>{const r=runtime(),a=r.propose();assert.throws(()=>r.ctx.ccExecute('valid',a.id),/APPROVAL_REQUIRED/);assert.throws(()=>r.ctx.ccDecide('valid',a.id,'wrong','approve'),/APPROVAL_NOT_APPLICABLE/);r.ctx.ccDecide('valid',a.id,a.payloadHash,'approve');assert.equal(r.ctx.ccExecute('valid',a.id).status,'succeeded');assert.equal(r.ctx.ccExecute('valid',a.id).status,'succeeded');assert.equal(r.saves(),1);});
test('AS-03 durable ledger survives a fresh process context',()=>{const r=runtime(),a=r.propose();const fresh=runtime(r.rows);assert.equal(fresh.propose().id,a.id);assert.equal(fresh.rows.length,2);assert.equal(fresh.ctx.ccState('valid').actions.length,1);});
test('AS-04 changed record blocks execution without dispatch',()=>{const r=runtime(),a=r.propose();r.ctx.ccDecide('valid',a.id,a.payloadHash,'approve');r.change();assert.throws(()=>r.ctx.ccExecute('valid',a.id),/STALE_RECORD/);assert.equal(r.saves(),0);});
test('AS-05 rejection cannot be executed or approved again',()=>{const r=runtime(),a=r.propose();r.ctx.ccDecide('valid',a.id,a.payloadHash,'reject');assert.throws(()=>r.ctx.ccExecute('valid',a.id),/RECONCILE_REQUIRED/);assert.throws(()=>r.ctx.ccDecide('valid',a.id,a.payloadHash,'approve'),/NOT_APPLICABLE/);});
test('AS-06 uncertain outcome persists and cannot be retried',()=>{const r=runtime(),a=r.propose();r.ctx.ccDecide('valid',a.id,a.payloadHash,'approve');r.ctx.saveRecordLocked_=()=>{throw Error('Timeout after possible write');};assert.equal(r.ctx.ccExecute('valid',a.id).status,'uncertain');const fresh=runtime(r.rows);assert.throws(()=>fresh.ctx.ccExecute('valid',a.id),/RECONCILE_REQUIRED/);assert.equal(fresh.saves(),0);});
test('AS-07 unsupported operations and protected fields are denied',()=>{const r=runtime();for(const operation of ['send','publish','delete','merge','deploy'])assert.throws(()=>r.ctx.ccPropose('valid',{...r.input,operation}),/UNSUPPORTED/);assert.throws(()=>r.ctx.ccPropose('valid',{...r.input,fields:{version:'overwrite'}}),/FIELD_NOT_ALLOWED/);});
test('AS-08 audit excludes raw fields and session credentials',()=>{const r=runtime();r.propose();const audit=JSON.stringify(r.ctx.ccState('valid').audit);assert.ok(!audit.includes('Prepared'));assert.ok(!audit.includes('valid'));assert.match(audit,/proposed/);});
test('AS-09 corrupted ledger fails closed',()=>{const r=runtime();r.propose();r.rows[1][3]+=' ';assert.throws(()=>r.ctx.ccState('valid'),/INTEGRITY/);});
test('AS-10 duplicate backend brief event produces one report and journal result',()=>{const r=runtime(),ctx={tenantId:'tss-test',actor:'internal'},build=()=>({status:'completed',sections:[],externalActionExecuted:false});const a=r.ctx.ccRunBriefCore_(r.ss,ctx,'daily-brief','daily:2026-09-22',build);const b=r.ctx.ccRunBriefCore_(r.ss,ctx,'daily-brief','daily:2026-09-22',()=>{throw Error('duplicate');});assert.equal(a.id,b.id);assert.equal(b.status,'completed');assert.equal(r.rows.length,3);});
test('AS-11 expired approval cannot execute',()=>{const r=runtime(),a=r.propose();r.ctx.ccDecide('valid',a.id,a.payloadHash,'approve');const e=JSON.parse(r.rows[2][3]);e.state.approval.expiresAt='2000-01-01';r.rows[2][3]=JSON.stringify(e);r.rows[2][4]=createHash('sha256').update(r.rows[2][3]).digest('hex');assert.throws(()=>r.ctx.ccExecute('valid',a.id),/APPROVAL_REQUIRED/);});
