import test from 'node:test';import assert from 'node:assert/strict';
import {operationalEvidence,notificationItems} from '../../command-center/context.js';
import {commandCenter} from '../../crm/command-center.js';
import {health} from '../../command-center/operations.js';
import {fixture,now} from './support.js';
test('CTX-01 message date alone does not establish ingestion success',()=>{const s=fixture();assert.equal(operationalEvidence(s)['Outlook ingestion'],undefined);s.records['Email Activity'][0].createdAt=now.toISOString();const e=operationalEvidence(s)['Outlook ingestion'];assert.equal(e.reference,'MSG-1');assert.equal(health(e,now).status,'unverified');});
test('CTX-02 notifications deduplicate exact action state and flag expired approval',()=>{const a={id:'A1',status:'proposed',approvalState:'approved',approval:{expiresAt:'2000-01-01'}};const n=notificationItems({actions:[a,a],jobs:[{id:'J1',type:'daily-brief',status:'failed'}]},now);assert.equal(n.length,2);assert.equal(n[0].kind,'Warning');assert.equal(n[1].kind,'Failed');});
test('CTX-03 Manager reads actual approval service and preserves unavailable state',async()=>{const s=fixture(),call=async()=>({actions:[{id:'A1',entity:'Tasks',operation:'update',status:'proposed',approvalState:'pending'}]});const ok=await commandCenter.answer('Show me what needs approval',s,{call});assert.match(ok,/A1/);assert.doesNotMatch(ok,/not connected/);const bad=await commandCenter.answer('Show me what needs approval',s,{call:async()=>{throw Error('offline');}});assert.match(bad,/Approval service unavailable/);});
test('CTX-04 daily and weekly combine growth communications content and approvals',async()=>{for(const q of ['What needs my attention?','Prepare my weekly management report']){const result=await commandCenter.answer(q,fixture(),{call:async()=>({actions:[],jobs:[]})});for(const label of ['CRM','Communications','Growth','Operations','Content','Approvals'])assert.ok(result.includes('<h3>'+label+'</h3>'));}});
