import test from 'node:test';import assert from 'node:assert/strict';
import {operationalEvidence,notificationItems} from '../../command-center/context.js';
import {commandCenter} from '../../crm/command-center.js';
import {health} from '../../command-center/operations.js';
import {fixture,now} from './support.js';

test('CTX-01 message date alone does not establish ingestion success',()=>{const s=fixture();assert.equal(operationalEvidence(s)['Outlook ingestion'],undefined);s.records['Email Activity'][0].createdAt=now.toISOString();const e=operationalEvidence(s)['Outlook ingestion'];assert.equal(e.reference,'MSG-1');assert.equal(health(e,now).status,'unverified');});
test('CTX-02 notifications deduplicate exact action state and flag expired approval',()=>{const a={id:'A1',status:'proposed',approvalState:'approved',approval:{expiresAt:'2000-01-01'}};const n=notificationItems({actions:[a,a],jobs:[{id:'J1',type:'daily-brief',status:'failed'}]},now);assert.equal(n.length,2);assert.equal(n[0].kind,'Warning');assert.equal(n[1].kind,'Failed');});
test('CTX-03 Manager reads actual approval service and preserves unavailable state',async()=>{const s=fixture(),call=async()=>({actions:[{id:'A1',entity:'Tasks',operation:'update',status:'proposed',approvalState:'pending'}]});const ok=await commandCenter.answer('Show me what needs approval',s,{call});assert.match(ok,/A1/);assert.doesNotMatch(ok,/not connected/);const bad=await commandCenter.answer('Show me what needs approval',s,{call:async()=>{throw Error('offline');}});assert.match(bad,/Approval service unavailable/);});
test('CTX-04 daily and weekly combine growth communications content and approvals',async()=>{for(const q of ['What needs my attention?','Prepare my weekly management report']){const result=await commandCenter.answer(q,fixture(),{call:async()=>({actions:[],jobs:[]})});for(const label of ['CRM','Communications','Growth','Operations','Content','Approvals'])assert.ok(result.includes('<h3>'+label+'</h3>'));}});

test('CTX-05 successful daily backup becomes healthy within the explicit backup window',()=>{const s=fixture();s.records['Automation Log']=[{timestamp:'2026-09-22T08:00:00Z',component:'CRM Backup',status:'Success',runReference:'BACKUP-1',resolved:'Yes'}];s.records['System Control'].push({setting:'backupEnabled',value:'ON'});const e=operationalEvidence(s).Backups;assert.equal(e.reference,'BACKUP-1');assert.equal(health(e,now).status,'healthy');});
test('CTX-06 persisted inbound enquiry proves receipt and one CRM transfer without inventing service health',()=>{const s=fixture();s.records.Activity.push({id:'ACT-WEB',recordId:'TSS-WEB-1',action:'Inbound enquiry',summary:'Website enquiry TSS-2026-0042 | Other',createdAt:'2026-09-22T08:30:00Z'});const e=operationalEvidence(s);assert.equal(e['Website enquiries'].reference,'TSS-2026-0042');assert.equal(e['CRM transfers'].reference,'TSS-WEB-1');assert.equal(health(e['Website enquiries'],now).status,'unverified');assert.equal(health(e['CRM transfers'],now).status,'unverified');});
test('CTX-07 unresolved automation warnings surface as a Jobs warning and resolved rows do not',()=>{const s=fixture();s.records['Automation Log']=[{timestamp:'2026-09-22T08:00:00Z',component:'CRM Health Check',status:'Warning',severity:'Warning',resolved:'No'},{timestamp:'2026-09-22T08:30:00Z',component:'CRM Backup',status:'Success',severity:'Info',resolved:'Yes'}];let e=operationalEvidence(s);assert.equal(e.Jobs.backlog,1);assert.equal(health(e.Jobs,now).status,'warning');s.records['Automation Log'][0].resolved='Yes';e=operationalEvidence(s);assert.equal(e.Jobs.backlog,undefined);assert.equal(health(e.Jobs,now).status,'unverified');});
test('CTX-08 production deployment control is evidence but not a substitute for live Vercel health',()=>{const s=fixture();s.records['System Control'].push({setting:'commandCenterProductionStatus',value:'LIVE',updatedAt:'2026-09-22T08:00:00Z'},{setting:'commandCenterDeploymentId',value:'dpl_test',updatedAt:'2026-09-22T08:00:00Z'});const e=operationalEvidence(s).Deployment;assert.equal(e.reference,'dpl_test');assert.equal(health(e,now).status,'unverified');});
