import test from 'node:test';import assert from 'node:assert/strict';
import {CRMAdapter} from '../../command-center/crm.js';import {Gateway} from '../../command-center/gateway.js';import {fixture,now,TestStore} from './support.js';
const crm=()=>new CRMAdapter(fixture());
test('P1-01 exact normalized company lookup',()=>assert.equal(crm().lookup('Example Surfaces').record.id,'SYN-1'));
test('P1-02 exact ID lookup',()=>assert.equal(crm().lookup('SYN-1').record.id,'SYN-1'));
test('P1-03 ambiguous name cannot choose a record',()=>assert.equal(crm().lookup('Example').status,'ambiguous'));
test('P1-04 unknown name cannot guess',()=>assert.equal(crm().lookup('Unknown').status,'unknown'));
test('P1-05 overdue task uses Cyprus date',()=>assert.ok(crm().attention(now).items.some(x=>x.kind==='overdue'&&x.id==='TASK-1')));
test('P1-06 missing next action',()=>assert.ok(crm().attention(now).items.some(x=>x.kind==='missing_next_action')));
test('P1-07 dormant opportunity uses configured 10 days',()=>assert.equal(crm().attention(now).items.find(x=>x.kind==='dormant').threshold,10));
test('P1-08 duplicate candidates never merge',()=>{const f=fixture();f.records.Companies.push({...f.records.Companies[0],id:'SYN-3'});const before=JSON.stringify(f);assert.ok(new CRMAdapter(f).quality().duplicates.length);assert.equal(JSON.stringify(f),before)});
test('P1-09 incomplete company',()=>assert.ok(crm().quality().issues.some(x=>x.id==='SYN-2'&&x.kind==='incomplete')));
test('P1-10 existing custom values preserved',()=>{const f=fixture();f.records.Companies[0].status='Custom approved value';new CRMAdapter(f).quality();assert.equal(f.records.Companies[0].status,'Custom approved value')});
test('P1-11 dossier has available communications',()=>assert.equal(crm().dossier('SYN-1').sections['Email Activity'].length,1));
test('P1-12 missing history not called empty',()=>{const f=fixture();delete f.records['Email Activity'];assert.equal(new CRMAdapter(f).dossier('SYN-1').coverage['Email Activity'].available,false)});
test('P1-13 unauthorized proposal rejected',async()=>{const g=new Gateway({store:new TestStore(),authorize:async()=>false,adapter:{}});await assert.rejects(g.propose({tenantId:'tss',actor:'test'},{}),/UNAUTHORIZED/)});
test('P1-14 record changes after approval rejected',async()=>{let writes=0;const g=new Gateway({store:new TestStore(),authorize:async()=>true,clock:()=>now,adapter:{validate:async()=>{},read:async()=>({version:2}),execute:async()=>{writes++}}});const ctx={tenantId:'tss',actor:'test'},a=await g.propose(ctx,{source:'crm',requestId:'R1',entity:'Companies',operation:'update',recordId:'SYN-1',fields:{name:'New'},expectedVersion:1,expectedOutcome:'Rename'});await g.approve(ctx,a.id,a.payloadHash);await assert.rejects(g.execute(ctx,a.id),/STALE_RECORD/);assert.equal(writes,0)});
test('P1-15 partial data retains limitations',()=>{const f=fixture();delete f.records.Tasks;delete f.records['System Control'];const r=new CRMAdapter(f).attention(now);assert.ok(r.limitations.some(x=>x.includes('Tasks')));assert.ok(!r.items.some(x=>x.kind==='dormant'))});
import {Manager} from '../../command-center/manager.js';
test('P1-16 Manager routes exact dossier without model guessing',async()=>{const r=await new Manager({crm:crm()}).run('Summarize SYN-1.',now);assert.equal(r.results[0].data.record.id,'SYN-1')});
