import test from 'node:test';import assert from 'node:assert/strict';import {health,enquiryStatus,contentDraft,reviewContent,publicationState} from '../../command-center/operations.js';import {Gateway} from '../../command-center/gateway.js';import {TestStore,now} from './support.js';
const good=()=>({format:'Feed',width:1080,height:1350,caption:'Customer follow-up',assetHash:'synthetic-hash',assetReference:'synthetic-only',logoReviewed:true,finalAssetReviewed:true});
test('P3-01 enquiry success requires linked CRM receipts',()=>assert.equal(enquiryStatus({enquiryId:'SYN-E1',crmSyncStatus:'Synced',linkedRecordIds:['SYN-1']}).status,'completed'));
test('P3-02 persisted enquiry with delayed transfer stays pending',()=>assert.equal(enquiryStatus({enquiryId:'SYN-E1',crmSyncStatus:'Pending'}).status,'pending'));
test('P3-03 failed transfer is visible',()=>assert.equal(enquiryStatus({enquiryId:'SYN-E1',crmSyncStatus:'Needs review'}).status,'failed'));
test('P3-04 repeated transfer observation has no write side effects',()=>{const r={enquiryId:'SYN-E1',crmSyncStatus:'Pending'};assert.deepEqual(enquiryStatus(r),enquiryStatus(r));assert.equal(r.crmSyncStatus,'Pending')});
test('P3-05 stale ingestion warns',()=>assert.equal(health({lastBusinessSuccess:'2026-09-20T00:00:00Z',maxAgeMs:3600000},now).status,'warning'));
test('P3-06 successful business job is healthy',()=>assert.equal(health({lastBusinessSuccess:now.toISOString(),maxAgeMs:3600000},now).status,'healthy'));
test('P3-07 job failure remains failed',()=>assert.equal(health({errorCode:'SYN_FAILURE'},now).status,'failed'));
test('P3-08 missing backup evidence stays unknown',()=>assert.equal(health(null,now).status,'unknown'));
test('P3-09 scheduler success is not business health',()=>assert.equal(health({schedulerRan:true},now).status,'unknown'));
test('P3-10 social concepts are Draft',()=>assert.equal(contentDraft(now).state,'Draft'));
test('P3-11 final assets and logo required for approval readiness',()=>{assert.equal(reviewContent(good()).ready,true);assert.equal(reviewContent({...good(),assetHash:null}).ready,false)});
test('P3-12 cancelled publication stays cancelled',()=>assert.equal(publicationState({state:'Cancelled'},null),'Cancelled'));
test('P3-13 Scheduled needs platform reference and time',()=>{assert.equal(publicationState({state:'Scheduled'},null),'In Review');assert.equal(publicationState({}, {scheduledId:'SYN-schedule',scheduledAt:now.toISOString()}),'Scheduled')});
test('P3-14 definite failure is Failed',()=>assert.equal(publicationState({}, {definiteFailure:true}),'Failed'));
test('P3-15 uncertain publication needs review',()=>assert.equal(publicationState({state:'Approved'}, {uncertain:true}),'In Review'));
test('P3-16 publication gateway prevents duplicate dispatch',async()=>{let calls=0;const g=new Gateway({store:new TestStore(),authorize:async()=>true,clock:()=>now,adapter:{validate:async()=>{},execute:async()=>{calls++;return{receipt:'SYN-post'}}}}),ctx={tenantId:'tss',actor:'test'};const a=await g.propose(ctx,{source:'operations',requestId:'R',entity:'Social',operation:'publish',fields:good(),expectedOutcome:'Publish once'});await g.approve(ctx,a.id,a.payloadHash);await g.execute(ctx,a.id);await g.execute(ctx,a.id);assert.equal(calls,1)});
test('P3-17 story and reel use 1080 by 1920',()=>{const items=contentDraft(now).items;assert.ok(items.filter(x=>x.format!=='Feed').every(x=>x.width===1080&&x.height===1920))});
test('P3-18 unverified landmark blocked',()=>assert.equal(reviewContent({...good(),landmark:'Cyprus landmark'}).ready,false));
test('P3-19 unsupported factual claim blocked',()=>assert.equal(reviewContent({...good(),claims:[{text:'Guaranteed returns'}]}).ready,false));
test('P3-20 real estate agency positioning blocked',()=>assert.equal(reviewContent({...good(),positioning:'real_estate_agency'}).ready,false));
