import test from 'node:test';
import assert from 'node:assert/strict';
import {makeHandler} from '../../api/crm-command.js';
const request=()=>({method:'POST',headers:{origin:'https://preview.example.test',host:'preview.example.test'},body:{fn:'ccState',args:['synthetic-session']}});
function response(){return {headers:{},setHeader(k,v){this.headers[k]=v;},status(s){this.code=s;return this;},json(v){this.body=v;return this;}};}
test('SEC-20 transport rejects absent sessions and unapproved operations before dispatch',async()=>{let calls=0;const h=makeHandler(async()=>{calls++;});for(const body of [{fn:'ccState',args:[]},{fn:'saveRecord',args:['synthetic-session']},{fn:'ccInstall',args:['synthetic-session']}]){const r=response();await h({...request(),body},r);assert.ok(r.code>=400);}assert.equal(calls,0);});
test('SEC-21 cross-origin and non-POST requests cannot dispatch',async()=>{let calls=0;const h=makeHandler(async()=>{calls++;});for(const req of [{...request(),method:'GET'},{...request(),headers:{origin:'https://attacker.test',host:'preview.example.test'}},{...request(),headers:{host:'preview.example.test'}}]){const r=response();await h(req,r);assert.ok(r.code>=400);}assert.equal(calls,0);});
test('SEC-22 ContentService redirect receives no session or POST body',async()=>{const calls=[];const h=makeHandler(async(url,opts)=>{calls.push({url,opts});return calls.length===1?new Response(null,{status:302,headers:{location:'https://script.googleusercontent.com/macros/echo?test=synthetic'}}):Response.json({ok:true,result:{version:'test'}});});const r=response();await h(request(),r);assert.equal(r.code,200);assert.equal(calls.length,2);assert.equal(calls[1].opts.method,'GET');assert.equal(calls[1].opts.body,undefined);assert.equal(calls[1].opts.headers,undefined);assert.equal(r.headers['Cache-Control'],'private, no-store');});
test('SEC-23 unexpected redirects are blocked without leaking session',async()=>{for(const location of ['https://attacker.test/','https://script.googleusercontent.com.attacker.test/','http://script.googleusercontent.com/','https://script.googleusercontent.com:8443/']){let calls=0;const h=makeHandler(async()=>{calls++;return new Response(null,{status:302,headers:{location}});});const r=response();await h(request(),r);assert.equal(calls,1);assert.equal(r.code,502);}});
test('SEC-24 uncertain external result never retries the mutation',async()=>{let calls=0;const h=makeHandler(async()=>{calls++;throw Error('synthetic-session secret');});const r=response();await h({...request(),body:{fn:'ccExecute',args:['synthetic-session','synthetic-action']}},r);assert.equal(calls,1);assert.equal(r.code,502);assert.ok(!JSON.stringify(r.body).includes('synthetic-session'));assert.match(r.body.error,/ledger/);});
test('SEC-25 backend auth failure remains a failure and HTML is not forwarded',async()=>{let r=response();await makeHandler(async()=>Response.json({ok:false,error:'AUTH_REQUIRED'}))(request(),r);assert.equal(r.body.ok,false);assert.equal(r.body.error,'AUTH_REQUIRED');r=response();await makeHandler(async()=>new Response('<html>private details</html>'))(request(),r);assert.equal(r.code,502);assert.ok(!JSON.stringify(r.body).includes('private details'));});

import vm from 'node:vm';
import {readFileSync} from 'node:fs';
test('SEC-26 browser relay retains same-origin Preview access without cross-origin credentials',async()=>{const html=readFileSync('crm/index.html','utf8');const source=html.slice(html.indexOf('async function rpc('),html.indexOf('async function call('));const calls=[];const c=vm.createContext({CRM_API:'https://script.google.com/synthetic',fetch:async(url,options)=>{calls.push({url,options});return{ok:true,json:async()=>({ok:true,result:{}})}}});vm.runInContext(source,c);await c.rpc('ccState','synthetic-session');await c.rpc('getState','synthetic-session');assert.equal(calls[0].url,'/api/crm-command');assert.equal(calls[0].options.credentials,'same-origin');assert.equal(calls[1].url,'https://script.google.com/synthetic');assert.equal(calls[1].options.credentials,'same-origin');});
